apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

namespace: project-template

resources:
  - namespace.yaml
  - rolebindings.yaml
