---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nv-icinga-monitoring:cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: icinga-monitor
  namespace: icinga-monitor
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io