---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icinga-monitor:view
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - endpoints
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - watch
  - describe
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - get
